- dashboard/src/scenes/stats/MedicalFilesStats.js
- dashboard/src/scenes/stats/PersonsStats.js
Voir : https://trello.com/c/PKEXPeR9/1337-avoir-la-possibilit%C3%A9-de-voir-les-personne-concern%C3%A9-en-cliquant-sur-la-statistique-stat-dossier-m%C3%A9dicale-et-consultation
> Les graphiques des statistiques médicales sont clicables (affichent les personnes concernées)

- dashboard/src/components/Notification.js
cf: https://trello.com/c/kabm9lmk/1319-la-cloche-m%C3%A9lange-les-commentaires-des-toutes-les-%C3%A9quipes-dune-orga
> Affichage des commentaires d'équipe uniquement dans la partie notification

- app/src/components/CustomFieldInput.js
- app/src/scenes/Territories/TerritoryObservationRow.js
- dashboard/src/components/CustomFieldDisplay.js
- dashboard/src/components/CustomFieldInput.js
- dashboard/src/components/Filters.js
- dashboard/src/components/TableCustomFields.js
- dashboard/src/recoil/evolutiveStats.ts
- dashboard/src/scenes/data-import-export/DownloadExample.js
- dashboard/src/scenes/data-import-export/ExportFormattedData.js
- dashboard/src/scenes/data-import-export/importSanitizer.js
- dashboard/src/scenes/organisation/view.js
- dashboard/src/scenes/person/MergeTwoPersons.js
- dashboard/src/scenes/report/components/ObservationsReport.js
- dashboard/src/scenes/stats/CustomFieldsStats.js
- dashboard/src/scenes/stats/ObservationsStats.js
- dashboard/src/scenes/stats/PersonsStats.js
- dashboard/src/types/field.ts
- dashboard/src/utils.js
- e2e/custom-fields_edit.spec.ts
Je doute un peu de l'apport (cu que c'est déjà par durée dans les stats) mais OK c'est XL dans l'excel
> Nouveau champ de type durée depuis une date

- dashboard/src/scenes/report/components/ActionsOrConsultationsReport.js
- dashboard/src/scenes/report/view.js
https://www.loom.com/share/a20ce80b926f4246a0b65173f7ebbe2d?sid=f25c5fbf-b06e-45d8-8196-3d29284ff24d
> Ajout de "Créée le" dans les filtres des actions et des consultations des comptes rendus

- dashboard/src/components/ActionStatusSelect.tsx
- dashboard/src/components/ActionsCalendar.js
- dashboard/src/components/ActionsSortableList.js
- dashboard/src/components/ActionsWeekly.js
- dashboard/src/recoil/actions.js
- dashboard/src/scenes/person/components/ActionsPerson.js
- dashboard/src/scenes/person/components/Consultations.js
- dashboard/src/scenes/search/index.js
- dashboard/src/types/action.ts
- e2e/consultations_with_teams.spec.ts
C'est prêt
~~Je bug complètement j'aurai besoin d'en parler. J'ai l'impression que pour pouvoir changer l'état dans ce composant je suis obligé de le faire réagir à l'ensemble des actions ce qui me semble absurde... Voir: https://manodiscussion.slack.com/archives/D02U0FGK3TJ/p1708435896239319~~
> Changement de statut à la volée

- dashboard/src/recoil/selectors.js
- dashboard/src/services/date.js
> Age en années, mois ou même jours

- app/src/components/Button.js
https://trello.com/c/RUinRdWe/1366-actions-dupliqu%C3%A9es-lors-de-saisie-multiples-dactions-pour-plusieurs-usagers
> Correction de la création multiple d'actions pour l'app

- dashboard/src/components/CommentsGeneric.js
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/132892/events/b12dac002eb348fab1391902a86d051a/\?project\=52\&referrer\=performance-trace-not-found
> possibilité de modifier un commentaire d'une consultation en cours de création

- dashboard/src/components/CommentsGeneric.js
https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/138772/\?project\=52\&query\=is%3Aunresolved\&referrer\=issue-stream\&stream_index\=21
> possibilité de modifier un commentaire d'un traitement en cours de création

- api/src/controllers/service.js
- dashboard/src/scenes/organisation/ServicesSettings.js
- e2e/reports_test-grouped-services.spec.ts
Sources : 
- https://trello.com/c/h5eFynTV/1350-vu-avec-arnaud-et-le-g-r%C3%A9cup%C3%A9rer-les-services-supprim%C3%A9s-par-le-boulet-de-lorganisation-esi-agora
- https://manodiscussion.slack.com/archives/C02U0F8CN0Y/p1708960602637269
> Quand on renomme un service, on ne fait plus disparaitre les anciens services enregistrés

- dashboard/src/components/ConsultationModal.js
- dashboard/src/scenes/person/components/TreatmentModal.js
- e2e/comments_medical.spec.ts
> possibilité de créer un commentaire/un document AVANT la création d'un traitement/consultation SANS MESSAGE D'ERREUR

- dashboard/src/components/CommentsGeneric.js
> amélioration de l'UI pour les commentaires non modifiables

- dashboard/src/components/SelectPerson.js
https://trello.com/c/z1P2M6aI/1375-bug-sélecteur-des-personnes-nest-pas-trié-par-ordre-alphabétique
> les personnes sont triées par nom dans le sélecteur de personnes pour la création d'action et autres

- api/src/controllers/organisation.js
- api/src/controllers/user.js
- dashboard/src/scenes/organisation/list.js
Le Y m'a demandé de créer trois comptes pour des orgas, je me suis dit que j'allais créer la fonctionnalité.
> Possibilité pour les super-admins de créer un utilisateur dans une orga existante

- dashboard/src/scenes/reception/SelectAndCreatePerson.jsx
https://www.notion.so/mano-sesan/En-tant-qu-AS-j-ai-besoin-d-avoir-une-alerte-sur-les-passages-lorsque-la-personne-en-question-est-d-0b8cd499d859427bad4423d1a3b98d3a?pvs=4
> Alerte sur les passages lorsque la personne en question est déjà passée

- api/src/controllers/user.js
- api/src/utils.js
- app/src/scenes/Login/ChangePassword.js
- dashboard/src/components/ChangePassword.jsx
Suite à une dicussion avec Guillaume
> feat: mise à jour des règles de mot de passe pour être conforme avec ce qui est écrit dans les docs (8 caractères)

- dashboard/package.json
- dashboard/yarn.lock
Je sais pas trop j'ai eu un truc bizarre avec eslint et c'est disparu. En tout cas, on peut se dire que c'est bien de mettre à jour les libs !
> chore: correction eslint bizarre

- dashboard/package.json
- dashboard/src/components/IncrementorSmall.jsx
- dashboard/yarn.lock
J'ai choisi une autre lib qui permet de flush
> fix: sauvegarder les services même quand on clique rapidement sur un autre service (en moins d'une seconde)

- dashboard/src/scenes/data-import-export/ExportFormattedData.jsx
https://www.notion.so/mano-sesan/Bug-export-des-consultations-Les-champs-sont-bien-remplis-dans-la-consultation-mais-dans-l-export-l-71e2c677536544d1abb757235f966f15?pvs=4
> fix: l'export des stats de consultation contient tous les champs, sans risque d'effacer des colonnes si plusieurs ont le même nom

- app/src/recoil/territory.js
- app/src/scenes/Territories/Territory.js
- dashboard/src/recoil/territory.js
- dashboard/src/scenes/territory-observations/list.jsx
- dashboard/src/scenes/territory/list.jsx
- dashboard/src/scenes/territory/view.jsx
~~Aïe, il va falloir mettre à jour les tests surement :'(~~
Bizarrement non 🤔
> feat: ajout d'une description des territoires et nouveau design de la page d'un territoire

- app/src/Navigators.js
- app/src/recoil/rencontres.js
- app/src/scenes/Persons/PersonsSearch.js
- app/src/scenes/Territories/TerritoryObservation.js
- app/src/scenes/Territories/TerritoryObservationRencontre.js
- dashboard/src/components/CreateObservation.jsx
- dashboard/src/components/Rencontre.jsx
- dashboard/src/recoil/rencontres.js
@arnaudambro Ça me semble OK pour une première itération et je pense qu'on peut améliorer ensuite. J'ai envie de sortir ça pour qu'on arrête de bloquer tout (car c'est la condition pour faire la mise à jour forcée du mobile dont on a besoin pour les constantes)
> feat: rencontres dans les observations

- app/src/Navigators.js
- app/src/scenes/Reports/PassagesForReport.js
- app/src/scenes/Reports/Report.js
- app/src/scenes/Reports/selectors.js
https://www.notion.so/mano-sesan/En-tant-que-pro-j-ai-besoin-d-avoir-les-passages-dans-les-CR-de-l-application-082b7d0635bd42b6846e62d26fcc8097
J'ai pas fait beaucoup d'effort sur le truc, mais maintenant on voit les passages :)
> feat: ajout des passages dans les rapport sur mobile

- dashboard/src/scenes/organisation/view.tsx
> feat: activation de la corbeille pour tout le monde

- dashboard/src/components/EvolutiveStatsSelector.tsx
- dashboard/src/components/Filters.tsx
- dashboard/src/types/field.ts
pourquoi ?
parce que je l'avais fait pour la PR #112 - j'avais rajouté dans `Filters.jsx` la fonction de  filtre par équipe améliorée, puis finalement je me suis dit que ça mélangeait trop les torchons et les serviettes, alors je l'ai retirée
> chore: Filters.jsx -> Filters.tsx

- dashboard/src/components/EvolutiveStatsViewer.tsx
> fix: graphique des stats évolutives qui faisait des bonds étranges

- dashboard/src/components/IncrementorSmall.jsx
https://mano-20.sentry.io/issues/5042249021/?alert_rule_id=15037906&alert_type=issue&environment=api-production&notification_uuid=6614a263-6c6a-4143-94f1-1faa586db564&project=4506672054140928&referrer=slack
> fix: pas de bug quand on rentre autre chose qu'un nombre dans les services MANO-API-5

- dashboard/src/scenes/stats/RencontresStats.jsx
- dashboard/src/scenes/stats/index.jsx
Voir : https://www.notion.so/mano-sesan/Bug-R-partition-des-rencontres-par-genre-ne-semble-pas-fonctionner-c60be17c9f464510868a099d5204bca5?pvs=4
> fix: correction du graphique de rencontres non-uniques par genre dans les stats qui était toujours vide

- dashboard/src/scenes/report/components/ObservationsReport.jsx
- dashboard/src/scenes/report/components/PassagesReport.jsx
- dashboard/src/scenes/report/components/PersonsReport.jsx
- dashboard/src/scenes/report/components/RencontresReport.jsx
> fix: suppression des titres en double dans les rapports

- app/src/services/api-interface-with-app.js
- app/src/services/api.js
- dashboard/src/services/api.js
possiblement lié à https://mano-20.sentry.io/issues/5077576277/?project=4506672157229056
> fix: fetch-retry seulement pour GET 🤯

- dashboard/__tests__/evolutives-stats-for-persons.test.ts
- dashboard/__tests__/mocks.ts
- dashboard/src/components/EvolutiveStatsViewer.tsx
- dashboard/src/recoil/evolutiveStats.ts
- dashboard/src/scenes/stats/PersonsStats.jsx
pas si simple ces stats évolutives
> feat: voir les personnes concernées par les stats évolutives

- dashboard/src/components/CreateObservation.jsx
- dashboard/src/scenes/reception/SelectAndCreatePerson.jsx
- dashboard/src/scenes/reception/view.jsx
Remplace https://github.com/mano-sesan/mano/pull/165
On fera le typescript plus tard
> fix: on retire l'accès au dossier de la personne dans la création d'une rencontre depuis une observation

- dashboard/src/scenes/stats/ObservationsStats.jsx
- dashboard/src/scenes/stats/index.jsx
J'aurai pu merger tout seul en ton absence, mais je ne sais pas : c'est surement que j'ai un doute si je suis passé par toi !
> feat: ajout dans les stats d'observations d'un graphique du nombre de personnes suivies uniques rencontrées dans un territoire

- dashboard/src/components/CreateObservation.jsx
- dashboard/src/components/Rencontre.jsx
> fix: désactivation de l'accès au dossier de la personne dans la sur-modale de rattachement de rencontre

- dashboard/src/components/ConsultationModal.jsx
- dashboard/src/config.js
- dashboard/src/scenes/person/components/MedicalFile.tsx
> chore: les constantes sont vraiment dispo

- api/src/db/migrations/20240425161918-add-lockedForEncryption-to-org.js
À faire avant https://github.com/mano-sesan/mano/pull/162
> chore: lancement de la migration qui ajoute la nouvelle colonne (à livrer en prod avant de livrer son utilisation)

- api/mocked-db.sql
- api/src/controllers/encrypt.js
- api/src/controllers/organisation.js
- api/src/middleware/validateEncryptionAndMigrations.js
- api/src/models/organisation.js
- api/src/utils/data-serializer.js
- dashboard/src/components/EncryptionKey.jsx
https://www.notion.so/mano-sesan/G-r-r-les-quelques-l-ments-victimes-de-ERROR-DECRYPTING-ITEM-Error-wrong-secret-key-for-the-give-b1228e8a274f44c28a68b499f5f93b51?pvs=4
> fix: verrouiller la BDD lors du téléchargement des éléments préalable au changement de clé

- dashboard/src/scenes/stats/ObservationsStats.jsx
> feat: ajout dans les stats d'observations d'un graphique du nombre de rencontres dans un territoire

- api/package.json
- dashboard/package.json
- package.json
- website/package.json
à défaut de rendre ça automatique...
au moins on saura dans Sentry si les utilisateurs sont à jour, un peu :)
> fix: version 2.0.0

- app/src/components/Document.js
- app/src/components/DocumentsManager.js
https://mano-20.sentry.io/issues/5041432893/?project=4506829687554048&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1
> fix: debug Cannot read property filename of undefined

- app/src/recoil/actions.js
- app/src/scenes/Actions/Action.js
- dashboard/src/components/ActionModal.jsx
- dashboard/src/components/CommentsGeneric.jsx
- dashboard/src/components/DocumentsGeneric.tsx
- dashboard/src/components/DocumentsOrganizer.tsx
- dashboard/src/recoil/actions.js
- dashboard/src/recoil/selectors.js
- dashboard/src/scenes/person/components/PersonDocuments.tsx
- dashboard/src/scenes/person/components/PersonDocumentsMedical.tsx
- dashboard/src/types/document.ts
- e2e/actions_comments_urgents.spec.ts
- e2e/actions_create-action-with-comment.spec.ts
- e2e/actions_crud.spec.ts
- e2e/comments_non-medical.spec.ts
- e2e/global_encryption-check-all-data-type.spec.ts
- e2e/restricted-role_V2.spec.ts
manque : afficher dans la liste des documents de la personne
> feat: ajout des documents dans les actions et refonte de la création/modification des actions

- dashboard/src/components/DataLoader.jsx
- dashboard/src/services/dataManagement.ts
https://mano-20.sentry.io/issues/5353179848/?project=4506672157229056&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0
https://mano-20.sentry.io/issues/5353363347/?project=4506672157229056&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=5
> fix: IndexedDB InvalidStateError

- api/src/index.js
- api/src/utils/userLogClean.js
ceci est une humble proposition de quick win, aucun problème à ce que ça soit recalé :)
> chore: supprime les logs utilisateurs à peu près au bout de 6 mois

- api/src/controllers/organisation.js
- api/src/db/migrations/20240516130346-default-persons-folders.js
- api/src/models/organisation.js
- api/src/utils.js
- api/src/utils/data-serializer.js
- dashboard/src/components/DocumentsGeneric.tsx
- dashboard/src/components/DocumentsOrganizer.tsx
- dashboard/src/scenes/organisation/DefaultPersonFolders.tsx
- dashboard/src/scenes/organisation/view.tsx
- dashboard/src/scenes/person/components/PersonDocuments.tsx
- dashboard/src/types/organisation.ts
C'est prêt c'était plus simple que prévu !
> feat: ajout de dossiers par défaut pour une organisation

- dashboard/src/components/ActionStatusSelect.tsx
- dashboard/src/components/ConsultationModal.jsx
- dashboard/src/components/CreateObservation.jsx
- dashboard/src/components/Notification.jsx
- dashboard/src/components/Passage.jsx
- dashboard/src/components/Rencontre.jsx
- dashboard/src/scenes/person/CreatePerson.jsx
- dashboard/src/scenes/person/OutOfActiveList.jsx
- dashboard/src/scenes/person/PersonFamily.jsx
- dashboard/src/scenes/person/Places.jsx
- dashboard/src/scenes/person/components/Comments.jsx
- dashboard/src/scenes/person/components/CommentsMedical.jsx
- dashboard/src/scenes/person/components/DeletePersonButton.jsx
- dashboard/src/scenes/person/components/EditModal.jsx
- dashboard/src/scenes/person/components/MedicalFile.tsx
- dashboard/src/scenes/person/components/PersonDocumentsMedical.tsx
- dashboard/src/scenes/person/components/TreatmentModal.jsx
- dashboard/src/scenes/person/list.jsx
- dashboard/src/scenes/person/view.jsx
- dashboard/src/scenes/reception/SelectAndCreatePerson.jsx
- dashboard/src/scenes/reception/view.jsx
- dashboard/src/scenes/report/components/Transmissions.jsx
- dashboard/src/scenes/territory/list.jsx
- dashboard/src/scenes/territory/view.jsx
- e2e/activate_passages_rencontres.spec.ts
Si les tests passent c'est bon :)
> fix: utilisation de refresh

- dashboard/src/scenes/person/components/MedicalFile.tsx
> fix: réparation de la taille des blocs traitements et documents dans le dossier médical (qui grossissaient à l'infini)

- dashboard/src/components/CommentsGeneric.jsx
- dashboard/src/components/ConsultationModal.jsx
- dashboard/src/scenes/person/components/Comments.jsx
- dashboard/src/scenes/person/components/CommentsMedical.jsx
- dashboard/src/scenes/person/components/TreatmentModal.jsx
https://www.notion.so/mano-sesan/En-tant-que-m-decin-j-aimerais-que-quand-je-cr-e-un-commentaire-lors-d-une-consultation-m-dicale-j-e85319106ab24a3399866379d5f7d89d?pvs=4
> feat: possibilité de partager les commentaires médicaux à des personnes non-médicales

- api/src/controllers/user.js
- api/src/db/migrations/20240524133312-user-login-attempt.js
- api/src/models/user.js
Pris d'ici : https://github.com/betagouv/service-national-universel/blob/main/api/src/auth.js
> feat: bloquer à la 4eme connexion infructueuse pendant 1 minute chaque fois, puis 1 heure à partir de 7eme, définitivement à la 13eme

- dashboard/src/components/DocumentsGeneric.tsx
https://mano-20.sentry.io/issues/5424272789/
> fix: évite une erreur lors d'un glisser déposé qui échoue (MANO-ESPACE-CV)

- dashboard/src/components/DataLoader.jsx
- dashboard/src/services/dataManagement.ts
Donc c'est une permière PR dans laquelle on vide juste les données du store.
Je propose de la livrer après ta review et ensuite je prépare une PR qui remplace le nom du store (désolé tout le monde) et gère la suppression historique de ce store...
> fix: amélioration du vidage du cache

- dashboard/src/components/DataLoader.jsx
- dashboard/src/services/dataManagement.ts
(à faire après : https://github.com/mano-sesan/mano/pull/255)
J'ai oublié de préciser : si ça marche et tu valides, c'est potentiellement cache remis à zéro pour tout le monde (hum d'ailleurs ça mérite un peu de test peut-être)
> feat: renommage de la base idb

- dashboard/src/components/ConsultationModal.jsx
https://www.notion.so/mano-sesan/Constantes-Ne-plus-limiter-la-saisie-de-tensions-Systolique-et-Diastolique-fbafb91831db4690a1322d193cb7a69f?pvs=4
> fix: plus de limite systolique et diastolique

- dashboard/src/scenes/user/view.jsx
https://www.notion.so/mano-sesan/Un-utilisateur-qui-n-a-pas-de-nom-n-est-pas-supprimable-29425b7c975c4724804014455222577a?pvs=4
> fix: demande confirmation de l'email de l'utilisateur avant de le supprimer

- dashboard/src/services/api.ts
https://mano-20.sentry.io/issues/5460989887/?project=4506672157229056&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0
> fix: if no result in api throw error

- dashboard/__tests__/evolutives-stats-for-persons.test.ts
- dashboard/src/components/EvolutiveStatsViewer.tsx
- dashboard/src/recoil/evolutiveStats.ts
- dashboard/src/scenes/stats/PersonsStats.jsx
- dashboard/src/services/dataManagement.ts
> fix: nouvelles stats évolutives

- api/src/controllers/action.js
- api/src/controllers/category.js
- api/src/controllers/collaboration.js
- api/src/controllers/comment.js
- api/src/controllers/consultation.js
- api/src/controllers/custom-field.js
- api/src/controllers/encrypt.js
- api/src/controllers/group.js
- api/src/controllers/medicalFile.js
- api/src/controllers/merge.js
- api/src/controllers/migration.js
- api/src/controllers/organisation.js
- api/src/controllers/passage.js
- api/src/controllers/person.js
- api/src/controllers/place.js
- api/src/controllers/relPersonPlace.js
- api/src/controllers/rencontre.js
- api/src/controllers/report.js
- api/src/controllers/service.js
- api/src/controllers/structure.js
- api/src/controllers/team.js
- api/src/controllers/territory.js
- api/src/controllers/territoryObservation.js
- api/src/controllers/treatment.js
- api/src/controllers/user.js
- api/src/controllers/utils.js
- api/src/errors.js
TODO: vérifier le mobile (si ça marche toujours bien avec ce changement)
> fix: passport renvoie du json, ce qui effacera une partie des erreurs, sans complexifier le front

- dashboard/src/utils/person-history.ts
https://mano-20.sentry.io/issues/5473462353/?alert_rule_id=15037910&alert_type=issue&environment=dashboard&notification_uuid=af4f4798-0a1a-445a-a285-5e61bb6ceb66&project=4506672157229056&referrer=slack
> chore: pas d'erreur quand pas d'historique

- api/src/controllers/user.js
- dashboard/src/scenes/auth/forgot.jsx
- dashboard/src/scenes/auth/reset.jsx
- dashboard/src/scenes/organisation/view.tsx
- e2e/global_login-fail.spec.ts
https://www.notion.so/mano-sesan/BUG-premi-re-connexion-1420d75486f94b4aacd50d70ab5b3e9e?pvs=4
> fix: renouvellement du lien de connexion si il est expiré

- dashboard/src/components/KeyInput.tsx
> fix: on ne propose pas de mettre la première lettre en majuscule par défaut

- dashboard/src/components/DocumentsGeneric.tsx
- dashboard/src/components/DocumentsOrganizer.tsx
- dashboard/src/types/document.ts
c'est pour pouvoir débugger demain avec l'utilisatrice qui a des problèmes
on retire le debug dès qu'on en aura plus besoin
> fix: bouton pour afficher les metadata d'un document

- dashboard/src/app.jsx
- dashboard/src/components/ScrollToTop.jsx
> fis: réparation du scroll top quand on change d'url

- dashboard/src/scenes/organisation/view.tsx
OK c'est mineur, mais je viens de me refaire avoir !
> fix: on ne pouvait pas cliquer sur "activer les passages" et "rencontres" pour cocher la case dans la conf de l'organisation

- dashboard/package.json
- dashboard/src/recoil/groups.ts
- dashboard/src/scenes/person/PersonFamily.tsx
- dashboard/src/types/group.ts
- e2e/persons_familles.spec.ts
j'allais attaquer le bug des familles avec la fusion des personnes lorsque je me suis aperçu que je ne comprenais pas les familles
j'ai donc fais cette petite modif pour mieux comprendre ce qui se passe
> fix: meilleurs guides pour créer des nouvelles relations familiales

- api/src/controllers/merge.js
- dashboard/src/scenes/person/MergeTwoPersons.jsx
https://www.notion.so/mano-sesan/Lorsque-des-personnes-suivies-sont-li-es-par-des-liens-familiaux-et-qu-il-y-a-fusion-de-dossier-entr-95aac581cd9840d3ad67644a314b976b?pvs=4
> fix: on ne fusionnait pas les familles lorsqu'on fusionnait des dossiers, maintenant c'est le cas

- dashboard/src/scenes/person/Places.jsx
- dashboard/src/scenes/person/view.jsx
- e2e/global_encryption-check-all-data-type.spec.ts
- e2e/global_restricted-roles.spec.ts
- e2e/persons_person-full-test-migrated-from-jest.spec.ts
- e2e/places.spec.ts
> feat: affichage des territoires dans la liste des lieux fréquentés d'une personne

- dashboard/src/scenes/person/PersonFamily.tsx
rien de bien particulier, c'est pour boucler la boucle
> fix: meilleure description quand on veut définir un lien familial entre une personne et... cette même personne

- dashboard/src/scenes/action/list.jsx
> feat: nouveau selecteur de type de consultation

- dashboard/src/scenes/stats/ActionsStats.jsx
> fix: affichage des filtres de stats d'action sur une même ligne pour gagner de la place

- dashboard/src/scenes/stats/charts.jsx
- e2e/activate_passages_rencontres.spec.ts
J'ai fait quelques tests, c'est cool si tu en fais aussi (impression, beaucoup de data, etc.)
Normalement il y a encore des pb mais pas de régressions
> fix: amélioration de la lisibilité des graphiques

- api/src/controllers/organisation.js
- api/src/controllers/territory.js
- api/src/db/migrations/20240702072126-add-column-territory-type.js
- api/src/models/organisation.js
- api/src/utils/data-serializer.js
- app/src/components/MultiCheckBoxes/TerritoryMultiCheckBoxes.js
- app/src/recoil/territory.js
- dashboard/src/recoil/territory.ts
- dashboard/src/scenes/data-import-export/DownloadTerritoriesImportExample.jsx
- dashboard/src/scenes/data-import-export/ImportTerritories.jsx
- dashboard/src/scenes/organisation/TerritoriesTypesSettings.jsx
- dashboard/src/scenes/organisation/view.tsx
- dashboard/src/scenes/territory/list.jsx
- dashboard/src/types/organisation.ts
Bon en fait ça va.
J'ai noté ici pour un test: https://github.com/mano-sesan/mano/issues/298#issuecomment-2202580425 (je vais probablement me faire un vendredi test où je rattraperai toutes les nouvelles fonctionnalités, j'aime bien les journées à thème)
> feat: type de territoires personnalisables

- dashboard/src/components/table.tsx
> fix: pour éviter que la flèche se retrouve en dessous quand on trie dans un tableau

- dashboard/src/components/SelectPerson.jsx
> feat: permettre de chercher une personne par son pseudo dans les selecteurs de personnes

- dashboard/src/components/CommentsGeneric.jsx
- e2e/actions_comments_urgents.spec.ts
- e2e/actions_create-action-with-comment.spec.ts
- e2e/comments_non-medical.spec.ts
- e2e/persons_familles.spec.ts
- e2e/persons_person-full-test-migrated-from-jest.spec.ts
- e2e/restricted-role_V2.spec.ts
Ce sera plus simple pour placer la suite, + ça résout un pb de label et d'input + un problème qui affichait tout le temps des options
> fix: affichage amélioré des boites d'options (commentaire urgent, familial, médical partagé) et correction de labels

- api/src/controllers/user.js
https://mano-20.sentry.io/issues/5354247775/events/oldest/\?alert_rule_id\=15037906\&alert_type\=issue\&environment\=api-production\&notification_uuid\=d8dc7eaa-49d9-40b8-aaaf-a6543a537cee\&project\=4506672054140928\&referrer\=oldest-event
> fix: MANO-API-E insert or update on table RelUserTeam violates foreign key constraint RelUserTeam_team_fkey

- api/src/utils/data-serializer.js
> chore: identifiant de l'organisation mis à jour depuis le back (il n'était pas rafraichi dans l'interface super admin)

- dashboard/src/scenes/person/components/EditModal.jsx
- dashboard/src/scenes/person/components/PersonHistory.jsx
~~Probablement que les tests vont pas passer pour les retraits d'équipe~~
> feat: motif de sortie d'équipe depuis la modification d'une personne

- api/src/controllers/structure.js
- dashboard/src/recoil/structures.js
- dashboard/src/scenes/data-import-export/DownloadStructuresImportExample.jsx
- dashboard/src/scenes/data-import-export/ImportStructures.jsx
- dashboard/src/scenes/organisation/view.tsx
- e2e/fusion_orga.spec.ts
- e2e/structures.spec.ts
la branche est mal nommée mais bon
> feat: import de structures

- dashboard/src/scenes/organisation/superadmin.jsx
…e qui a déjà des équipes, ça plantait silencieusement
> fix: quand on crée un utilisateur sans équipes dans une orga existante qui a déjà des équipes, ça plantait silencieusement

- api/src/controllers/report.js
- dashboard/src/scenes/report/components/Transmissions.jsx
> feat: fusion des transmissions si deux personnes les remplissent en même temps

- dashboard/src/app.jsx
- dashboard/src/scenes/auth/signin.jsx
> feat: redirection vers la page où on était quand on a besoin de s'authentifier

- dashboard/src/scenes/organisation/superadmin.jsx
> fix: la page organisation ne s'affiche pas si on y va par erreur alors qu'on n'est pas super admin

- api/src/db/migrations/20240822133951-recompute-organisation-regions.js
Attention ! A faire après les autres PR et surtout à tester en local avant !
> feat: migration de toutes les villes existantes vers régions

- api/src/controllers/organisation.js
> chore: optimisation des requêtes superadmin (comme on n'affiche plus rapport, traitement et territoire)

- dashboard/src/scenes/stats/ConsultationsStats.jsx
> fix: dans les stats de consultations, si on cliquait sur un élément d'un histogramme (liste de valeur) on ne voyait pas la liste des consultations

- app/src/components/ListEmptyContainer.js
- app/src/scenes/Reports/Consultations.js
- dashboard/src/scenes/stats/ConsultationsStats.jsx
> chore(internal): confusion du mot consultation et action dans les variables

- dashboard/src/scenes/stats/PassagesStats.jsx
> feat: possibilité de cliquer dans les stats sur nombre de personnes nouvelles/différentes passées

- api/src/controllers/organisation.js
- dashboard/src/scenes/organisation/superadmin.jsx
> feat: stats sur les utilisateurs

- api/src/controllers/user.js
- dashboard/src/scenes/organisation/SuperadminOrgationsationUsers.tsx
- dashboard/src/scenes/organisation/superadmin.jsx
> feat: possibilité de modifier un utilisateur (et donc son role) depuis l'interface super admin

- dashboard/src/components/ButtonCustom.tsx
- dashboard/src/scenes/action/list.jsx
> fix: les boutons d'ajout ne sont plus élargis quand le nombre d'équipes sélectionnées est important dans l'agenda

- e2e/global-cache-isolated-browsers.spec.ts
> chore: j'avais oublié de push un commit

- dashboard/src/components/CreateObservation.tsx
- dashboard/src/components/Rencontre.jsx
> fix: modification d'une rencontre pas enregistrée sur une observation de territoire

- app/package.json
- app/src/recoil/selectors.js
- app/src/scenes/Actions/ActionsList.js
- app/src/scenes/Actions/ActionsTabNavigator.js
- app/yarn.lock
TODO, mais dans une autre PR 
- optimisation du calcul des actions: je retire ce que j'ai dit sur l'optimisation, on n'a pas encore fait tout ce qu'on pouvait faire: on a fait ce qu'on pouvait sur l'affichage (lazy, etc) mais on fait encore plusieurs loop sur l'ensemble des actions, on peut faire mieux
- affichage de TOUTES les actions à faire - mais pas sûr que ça soit indispensable - à voir
> feat(app): nouvelle navigation dans les actions à faire

- app/src/components/Search.js
On a un warning tout le temps dans la console
> chore: remove default prop warning

- app/src/components/ScrollContainer.js
- app/src/scenes/Actions/Action.js
Je me suis beaucoup fait aider par cursor. j'ai l'impression que ça marche
Mais j'ai aussi l'impression que dans notre react-native il y a plein de choses à penser à mettre dans les params etc. pour des edge cases.
> feat: les actions ont maintenant un système d'onglets

- dashboard/src/recoil/persons.ts
…
Je sais pas si c'est une super idée, ça met sous le tapis on dirait jsp
> fix: MANO-ESPACE-1ZN erreur pour solidatité 63 sur certains noms de personnes

- api/src/controllers/user.js
- app/src/Navigators.js
- app/src/components/Loader.js
- app/src/scenes/Actions/Action.js
- app/src/scenes/Login/Login.js
- app/src/scenes/Persons/Consultation.js
- app/src/scenes/Persons/Person.js
- app/src/scenes/Persons/PersonRow.js
- app/src/scenes/Persons/PersonSummary.js
- app/src/scenes/Persons/PersonsList.js
- app/src/scenes/Reports/Report.js
- app/src/utils/search.js
Source: https://www.notion.so/mano-sesan/R-les-dans-Mano-1298b26a1ed88083baf6cf93b2177fe4
> feat: acces restreint sur mobile

- api/src/controllers/user.js
- api/src/db/migrations/20241121000000-add-deleted-at-to-users.js
- api/src/models/user.js
- dashboard/src/components/CommentsGeneric.tsx
- dashboard/src/components/UserName.jsx
- dashboard/src/recoil/auth.ts
- dashboard/src/scenes/auth/signin.jsx
- dashboard/src/scenes/person/components/PassagesRencontres.jsx
EN fait j'ai pris une approche vachement plus simple et qui ne va pas alourdir le transport (càd :  rajouter userName partout). À ta dispo pour en parler moi je suis complètement convaincu.
En bref : lors de la suppression d'un utilisateur on soft delete + supprime tout le contenu des champs, sauf le nom.
Next steps si on part là dessus : mobile (rapide à faire) + supprimer le système qui rajoute le nom
> feat: affichage des noms des utilisateurs même quand ils ont été supprimés

- dashboard/src/components/ConfirmModal.tsx
- dashboard/src/components/DeleteButtonAndConfirmModal.tsx
- dashboard/src/scenes/team/view.jsx
- e2e/transfer_team.spec.ts
> feat: modale de confirmation pour le transfert d'équipe

- dashboard/src/app.jsx
> chore: ignore failed to fetch errors

- app/src/components/Recurrence.js
- app/src/scenes/Actions/NewActionForm.js
Par contre je n'ai pas fait (encore) de modification en masse comme sur la version web, parce que ça pose beaucoup de questions d'interface.
> feat(app): possibilité de créer des actions récurrentes sur mobile

- dashboard/src/scenes/report/components/CommentsReport.jsx
Pas très importants mais j'en aurai besoin pour ajouter les filtres
> fix: marge sur la liste des commentaires en plein écran dans les rapports

- dashboard/src/components/CustomFieldDisplay.jsx
- dashboard/src/components/HelpButtonAndModal.jsx
- dashboard/src/scenes/person/components/Constantes.tsx
- dashboard/src/scenes/person/components/PersonCustomFields.tsx
demandé par les utilisateurs pendant la présentation de Simon cette après-midi, j'ai fait ça dans mon coin
à valider avec toi et avec l'équipe avant de merge !
> feat: on peut voir l'historique d'un seul champ, en mode diagramme pour un chiffre, et un tableau pour le reste

- app/src/scenes/Reports/Collaborations.js
- app/src/scenes/Reports/Report.js
> feat(app): renommage de collaboration en co-intervention ppur harmoniser avec l'espace web

- dashboard/src/components/ActionModal.jsx
- dashboard/src/components/ConsultationModal.jsx
> feat: duplication des documents dans les actions et consultations créées après annulation

- app/src/services/api.js
> fix: on remonte aussi sur mobile les échecs et succes de déchiffrement (ce n'était pas le cas avant)

- .github/workflows/playwright.yml
> chore: màj de github action de playwright à v4 parce qu'il ne se lance plus sur github (obsolete)

- dashboard/src/scenes/person/components/PassagesRencontres.jsx
> fix: passage et rencontres sont maintenant ordonnés du plus récent au plus ancien dans la popup depuis le dossier de la personne

- dashboard/src/scenes/person/components/PersonDocuments.tsx
> fix: MANO-ESPACE-211 quand un utilisateur essaie de voir des documents d'un groupe qui ne contient (plus?) personne

- dashboard/src/scenes/auth/signin.jsx
> fix: un admin n'a pas toujours (voir jamais) d'organisation (et avec l'otp on n'a pas l'info de toute façon)

- dashboard/src/scenes/person/components/PassagesRencontres.jsx
> feat: possibilité de cliquer sur le nom d'un territoire dans une rencontre pour pouvoir ouvrir l'observation liée

- dashboard/src/components/ConfirmModal.tsx
> fix: espaces multiples et de toutes sortes acceptés dans la suppression d'un élément (par exemple si on a des espaces insécables ou des tabulations)

- dashboard/src/recoil/selectors.js
This reverts commit 55f3beb3171cb85e9f594edd5c54b490330d2dc9.
> fix: revert #959 (55f3beb3171cb85e9f594edd5c54b490330d2dc9)

- dashboard/src/scenes/person/PersonFamily.tsx
> fix: désactivation des liens pendant la suppression, modification, enregistrement des liens familiaux

- app/src/scenes/Persons/Documents.js
> fix: les documents des personnes n'étaient plus visible dans l'app (fix de #947)

- dashboard/src/services/dataLoader.js
> fix: race condition sur le dataloader entre les stats et le now (potentiellement intéressant pour les problèmes de cache)

- dashboard/package.json
- dashboard/src/scenes/organisation/superadmin.jsx
- dashboard/yarn.lock
> feat: vue diff sur les changements de configuration des organisations
