mano-sesan/mano

dashboard/src/scenes/data-import-export/ImportConfig.tsx
Voir: https://trello.com/c/cJH4wztG/1364-chu-hameau-arm%C3%A9e-du-salut-marseille-bug-fichier-dimport-param%C3%A9trage
=> Correction d'import de config pour ne pas créer deux champs avec un même identifiant

api/src/db/migrations/20240213155901-fix-duplicate-config-names.js
ça va avec celle là : https://github.com/mano-sesan/mano/pull/7
Elle sera à lancer sur la prod de l'ancien mano pour corriger ce trello : https://trello.com/c/cJH4wztG/1364-chu-hameau-arm%C3%A9e-du-salut-marseille-bug-fichier-dimport-param%C3%A9trage
Donc je ferai un cherry-pick dans l'autre sens
=> Correction rétroactive d'import de config pour ne pas créer deux champs avec un même identifiant

dashboard/src/app.js
=> Mano n'est plus accessible sans by-pass-redirect dans le local storage

dashboard/src/scenes/report/view.jsx
Voir: https://www.notion.so/mano-sesan/Bug-affichage-des-passage-6f539d3706c04b27b1290a39763d91e5
=> fix: on n'inclus pas les passages qui n'ont pas de date dans les rapports (reste à savoir pourquoi ils n'en ont pas)

dashboard/__tests__/evolutives-stats-for-persons.test.ts, dashboard/src/recoil/evolutiveStats.ts
avant: 
il faut constater que le 23/09/2022, certaines personnes sont Non renseignées ET RSA par exemple - pas possible
après:
=> fix: gère le cas où la date de départ est la même qu'une date de l'historique

dashboard/src/recoil/selectors.js, dashboard/src/scenes/stats/ActionsStats.jsx, dashboard/src/scenes/stats/GeneralStats.jsx, dashboard/src/scenes/stats/index.jsx
Voir: https://www.notion.so/mano-sesan/Bug-stat-fil-active-action-69ddbf65b1cd438da6fe859ad336d8a2
Et des discussions sur slack dont : https://manodiscussion.slack.com/archives/C02U0F8CN0Y/p1712914917835769
PS : désolé pour les modifs sur le premier fichier je peux les virer j'ai l'impression que c'est mon éditeur qui a fait ça. comme ça m'arrange bien, je laisse mais je peux vierer
=> fix: le nombre de personnes suivi ayant reçu une action est basé sur le nombre de personnes suivies

e2e/consultations_create-consultation-from-agenda.spec.ts
Je ne comprends même pas comment ça pouvait marcher ... Dans la saisie d'écran ci-dessous, la consultation n'a pas du tout comme texte "Consultation Médicale"... J'imagine qu'il devait y avoir quelque chose qui se passait "rapidement". En tout cas, je pense que c'est mieux comme ça
=> fix: correction d'un test automatisé

dashboard/src/scenes/territory-observations/list.jsx
Voir: [date de création au lieu de la date d'observation](https://www.notion.so/mano-sesan/Bug-dates-observation-99df4b337cfa4744adda78bc7f68dc00?pvs=4)
=> fix: les observations de territoire dans le dashboard affichaient la date de création au lieu de la date d'observation

dashboard/src/recoil/evolutiveStats.ts, dashboard/src/scenes/person/components/PersonHistory.jsx
je pense qu;'on a d'autres problèmes avec l'historique, peut-être qu'un clean sera nécessaire, après résolution
pourquoi je dis d'autres problèmes ?
- on a cette erreur sur sentry: https://mano-20.sentry.io/issues/5144987024/?environment=dashboard&project=4506672157229056&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0
- ça concerne Alexia (org test), et effectivement y'a une incohérence d'historique sur les Ressources, difficile à comprendre
bon en attendant, je cherche à reproduire l'historique qui pète, mais je ne vois pas
=> fix: affiche l'historique sans les doublons le cas échéant

dashboard/src/services/dataManagement.js
Je veux bien ton avis quand même @arnaudambro 
Pourquoi je l'ai try/catch vs ignorer dans sentry : parce que je pense que ça ne doit pas impacter le user. Ça bug quand ya rien sur certains navigateurs
=> fix: masquage de l'erreur localforage MANO-ESPACE-2E

dashboard/src/components/ActionModal.jsx, dashboard/src/components/ConsultationModal.jsx, dashboard/src/components/DatePicker.tsx, dashboard/src/scenes/person/OutOfActiveList.jsx, dashboard/src/scenes/person/components/EditModal.jsx, dashboard/src/scenes/person/components/TreatmentModal.jsx, e2e/persons_person-full-test-migrated-from-jest.spec.ts
https://www.notion.so/mano-sesan/Bug-Traitements-bf6bcb99936a4f79a38324488aecfb3e?pvs=4
le comportement qui frustre, c'est dire qu'il y a une erreur quelque part mais non ne sait pas forcément où
j'ai touché
- aux éléments qui ont plusieurs tabs (ActionModal, ConsultationModal et TraitementModal)
- à la Personne Suivie, qui a des `panels`
- à la modale de sortie de file active, qui se ferme même si la date rentrée est non valide
=> fix: oriente vers les champs non valides (ouvre la tab concernée) lorsqu'on tente d'enregistrer mais qu'ils sont non valides

dashboard/src/components/DataLoader.jsx
fixera probablement https://mano-20.sentry.io/issues/5054090483/activity/?project=4506672157229056&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=10
j'ai réussi à reproduire localement le fait d'avoir une `ERROR DECRYPTING ITEM` lorsqu'un autre utilisateur change la clé, et que je veux rafraichir mes données - vu que j'ai la mauvaise clé, j'ai une erreur de déchiffrement
=> fix: lorsque la clé de chiffrement change, ne plus charger de donnée tant que l'utilisateur n'a pas rechargé sa page

dashboard/src/components/EncryptionKey.jsx
on a pas besoin de ce refreshn puisque de toutes façons on retélécharge tout depuis le serveur une fois qu'on a renseigné la nouvelle clé
PS: c'est une PR préalable à la PR #265
=> chore: pas besoin de refresh dans le rechiffrement

dashboard/src/app.jsx
Voir https://stackoverflow.com/questions/55738408/javascript-typeerror-cancelled-error-when-calling-fetch-on-ios
=> chore: on ignore les erreur d'annulation manuelle de requête par l'utilisateur MANO-ESPACE-22

dashboard/src/services/dataManagement.ts
En attendant de faire un truc qui vient du back (et d'ailleurs je me demande si on en a tant besoin maintenant qu'on peut voir dans quelle release sont les gens directement, que ce soit dans sentry ou même dans le code grâce à VERSION, et que donc on peut complètement jouer avec ça) je pense qu'il faut refresh le cache pour pouvoir déteter quels sont les vrais problèmes encore en cours avec les éléments indéchiffrable pour les restaurer ?
Ça te va ?
=> chore: reset cache à l'ancienne (ce qui nous permettra de voir les gens qui ont toujours le problème après ça)

dashboard/src/components/DatePicker.tsx, dashboard/src/scenes/person/OutOfActiveList.jsx, dashboard/src/scenes/person/OutOfActiveListBanner.tsx, dashboard/src/scenes/person/components/PersonHistory.jsx, dashboard/src/scenes/person/view.jsx, e2e/persons_person-full-test-migrated-from-jest.spec.ts
En fait on va y aller pas à pas c'est plus prudent. Cette PR ajoute : 
- La possibilité de choisir de sortir d'une équipe quand on a cliqué sur "sortie de file active"
- L'affichage d'un bandeau quand on a quitté une équipe quelque part dans l'historique qui dit qu'on a quitté la file active de l'équipe pour telle raison (si la raison est présente)
Les étapes suivantes seront : 
- Possibilité de rajouter une raison quand on sort d'une équipe depuis la fiche de la personne
- (peut-être) choix de date de sortie
- affichage dans la liste des personnes quand une personne n'est pas dans la team en cours
- Dans l'app, afficher le bandeau aussi (je ne sais plus comment ça marche)
- Ajouter des tests sur tout ça
Je note tout ça dans le ticket
=> feat: sortie de file active par équipe, première étape

dashboard/src/components/Filters.tsx
A priori il n'y a pas de raison au fait de limiter le titre de la liste des filtres à 5/6, ce qui faisait un affichage bizarre dans les stats
_Plus tard on pourrait même challenger que ce titre soit dans le composant_
=> fix: pas de limite au titre de la liste des filtres

dashboard/src/components/Card.jsx, dashboard/src/components/HelpButtonAndModal.jsx, dashboard/src/scenes/stats/Blocks.jsx, dashboard/src/scenes/stats/ConsultationsStats.jsx, dashboard/src/scenes/stats/CustomFieldsStats.jsx, dashboard/src/scenes/stats/GeneralStats.jsx, dashboard/src/scenes/stats/ObservationsStats.tsx, dashboard/src/scenes/stats/PersonsStats.jsx
En fait ça devenait compliqué à maintenir parce que le conditionnement de l'affichage des boites dans leur container était dans les boites elles mêmes. Maintenant c'est l'extérieur qui défini s'il y a une grille, et son formattage. Autrement dit les boites sont libre de s'afficher dans ce qu'elles veulent (ça fait du code en moins).
Et j'ai enlevé (sorti) un gros if de "additionnal column" qui complexifiait
=> fix: nettoyage et harmonisation des boites

dashboard/src/components/UserName.jsx
c'est par rapport à cette carte https://www.notion.so/mano-sesan/Les-documents-n-ont-pas-le-cr-par-2ba39f7854ca4544aaf7a783c3789254?pvs=4
mais je propose uen solution globale...
pas sûr de mon coup, mais j'ai l'impression que c'est une bonne idée ?
=> fix: on affiche "Utilisateur supprimé" au lieu d'un espace vide

dashboard/package.json, dashboard/src/app.jsx, dashboard/src/components/DataLoader.jsx, dashboard/src/services/api.ts, dashboard/yarn.lock
Ça peut paraitre dingue mais j'y ai passé ma journée 😭 
Normalement ça corrige la plupart des anomalies "normales" de failed to fetch, principalement concernant les requêtes qui partent dans le vide.
- On ne fait plus de "focus" quand rafraichit la page (en cliquant sur rafraichir ou F5 ou CMD+R etc.)
- On annule les requêtes du dataloader
Pour tester je me suis mis en slow 3g et ça marche plutôt bien, j'arrive à éviter les erreurs dans la plupart des cas.
=> fix: meilleure gestion des requêtes avortées (failed to fetch, load failed, abort, etc.)

dashboard/src/scenes/person/components/EditModal.jsx
ça faisait une référence circulaire à un élément de DOM 🤯
=> fix: erreur quand on cliquait sur "ignorer cette étape" dans le retrait d'une équipe

dashboard/src/components/DataLoader.jsx
les logs dans sentry nous montrent que tout va bien, cad
- storedOrganisationId === user.organisation
or il semblerait que non puisqu'une erreur sur sentry nous dit que des personnes avec une autre `organisation` sont chargées
donc ce commit est pour avoir plus de logs
=> chore: plus d'info en cas d'orga mélangée dans le cache

app/src/recoil/selectors.js
AVANT: les actions à venir sont mal triées
APRÈS
=> fix: tri des actions dans l'app

dashboard/src/scenes/reception/SelectAndCreatePersonForReception.jsx
`Expectation Violation: Duplicate atom key "searchablePersonsSelector". This is a FATAL ERROR in production.`
=> chore: fix searchablePersonsSelectorForReception

dashboard/src/services/encryption.js
ça va nous permettre 
- de cibler l'erreur de déchiffrement sur un seul item, et d'enquêter sur cet item quand il arrive
- de ne pas se faire spammer par des problèmes résolus, comme c'est le cas actuellement
=> chore: nouveau message sentry pour les erreurs de dechiffrement

api/src/controllers/utils.js
En fait c'est le nom "mise-à-jour" qui peut avoir des tirets dans certains cas.
Mais pas le verbe.
=> chore(typo): mettre-à-jour vs mettre à jour

dashboard/src/services/dataLoader.js
To diagnose why the loader might be stuck in the isLoading === true state, let's examine the loadOrRefreshData function and related logic. Here are some potential areas where the state might not be reset properly:
Error Handling: If an error occurs during data fetching, the resetLoaderOnError function is called. This function should reset the loader state, but if it doesn't complete successfully, isLoading might remain true.
Early Returns: There are several return false; statements in the loadOrRefreshData function. If any of these are triggered without resetting the loader state, isLoading will remain true.
Final State Reset: The function should reset the loader state at the end of a successful data load. This is done with:
setIsLoading(false);
If this line is not reached due to an error …
=> fix: loading false a chaque fin de chargement

dashboard/src/services/dataLoader.js
explication du pourquoi du comment du bug: 
- quand on annule une fonction, et qu'on veut demande `Cette action est annulée, voulez-vous la dupliquer ?`, il y a toute une fonction qui duplique cette action, et à la fin de cette fonction se passe `await refresh();`
- MAIS
- ce refresh prenait les valeurs `actions` qui étaient AVANT la modification de l'action originale en statut Annulé (merci React j'imagine)
solution:
au lieu de 
```
const [actions, setActions] = useRecoilState(actionsState);
...
setActions(mergeItems(actions, newActions))
```
```
const setActions = useSetRecoilState(actionsState);
...
setActions((latestActions) => mergeItems(latestActions, newActions))
```
j'ai bien galéré
=> fix: une action replanifiée après annulation conserve ne conservait pas son statut annulé

app/src/services/encryption.js, dashboard/src/services/encryption.js, e2e/global_encryption-check-all-data-type.spec.ts
Testé sur mobile : j'ai créé des éléments avec des slashes, modifiés des éléments existants (créé sur le web) avec des slashes et chiffré plusieurs fois l'organisation. Tout semble fonctionner.
Voir aussi la discussion ici : https://manodiscussion.slack.com/archives/D02U0FGK3TJ/p1744624996600359
=> fix: gestion des slash lors du rechiffrement (version alternative pour tester)

dashboard/src/app.jsx, dashboard/src/components/DocumentsGeneric.tsx, e2e/documents_organizer.spec.ts
```mermaid
graph TD
A["User selects/drops files"] --> B["handleFilesUpload function"]
B --> C["Initialize upload progress"]
C --> D["Show modal with blurred background"]
D --> E["For each file:"]
E --> F["Set status to 'uploading'"]
F --> G["Encrypt file"]
G --> H["Upload to API"]
H --> I{Upload successful?}
I -->|Yes| J["Set status to 'completed'"]
I -->|No| K["Set status to 'error'"]
J --> L["Update progress bar"]
K --> L
L --> M{More files?}
M -->|Yes| E
M -->|No| N["Wait 1 second"]
N --> O["Close modal"]
O --> P["Show success toast"]
Q["UploadProgressProvider<br/>(Global component in App)"] --> R["UploadProgressModal<br/>(Renders progress UI)"]
R --> S["Blurred background<br/>prevents user interaction"]
style A fill:#e1f5fe
style D fill:#fff3e0
style S fill:#ffebee
style P …
```
=> feat: ajout d'une modale de chargement (avec progression) pour bloquer l'utilisation de la plateforme pendant l'envoi de documents
